## files and dirs excluded from analysis
exclude_patterns:
- "test*"


## actual check/plugin settings (required if .codeclimate.yml exists)

version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 505
  method-complexity:
    config:
      threshold: 18
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
